var BOROUGHS = <String>['Aberfeldy Village',
  'Acton',
  'Archway',
  'Balham',
  'Battersea',
  'Bayswater',
  'Belgravia',
  'Bellingham',
  'Belsize Park',
  'Bermondsey',
  'Bethnal Green',
  'Blackheath',
  'Bloomsbury',
  'Bow',
  'Brixton',
  'Brixton Hill',
  'Brockley',
  'Bromley-by-Bow',
  'Camberwell',
  'Camden Town',
  'Canonbury',
  'Chalk Farm',
  'Chelsea',
  'Chiswick',
  'City of London',
  'City of Westminster',
  'Clapham', 'Clapton',
  'Clerkenwell',
  'Covent Garden',
  'Crystal Palace',
  'Dalston',
  'De Beauvoir Town',
  'Deptford',
  'Earls Court',
  'East Dulwich',
  'Farringdon',
  'Finsbury Park',
  'Fish Island',
  'Fitzrovia',
  'Forest Hill',
  'Fulham',
  'Globe Town',
  'Greenwich',
  'Hackney',
  'Haggerston',
  'Hammersmith',
  'Hampstead',
  'Harringay Ladder',
  'Hendon',
  'Herne Hill',
  'Holborn',
  'Holland Park',
  'Isle of Dogs',
  'Islington',
  'Kennington',
  'Kensington',
  'Kings Cross',
  'Knightsbridge',
  'Lambeth',
  'LB of Barking and Dagenham',
  'LB of Barnet',
  'LB of Bexley',
  'LB of Brent',
  'LB of Bromley',
  'LB of Camden',
  'LB of Croydon',
  'LB of Ealing',
  'LB of Enfield',
  'LB of Hackney',
  'LB of Haringey',
  'LB of Harrow',
  'LB of Havering',
  'LB of Hillingdon',
  'LB of Hounslow',
  'LB of Islington',
  'LB of Merton',
  'LB of Newham',
  'LB of Redbridge',
  'LB of Richmond upon Thames',
  'LB of Sutton',
  'LB of Tower Hamlets',
  'LB of Waltham Forest',
  'Leamouth Peninsula', 'Lee',
  'Lewisham',
  'Lillington and Longmoore Gardens',
  'Limehouse',
  'Lisson Grove',
  'Lower Clapton',
  'Lower Streatham',
  'Maida Vale',
  'Marylebone',
  'Mayfair',
  'Mile End',
  'Millbank',
  'New Cross',
  'Nine Elms',
  'Norbury',
  'North Maida Vale',
  'Norwood',
  'Notting Hill',
  'Nunhead',
  'Paddington',
  'Palais Royal',
  'Parsons Green',
  'Peckham',
  'Pimlico',
  'Poplar',
  'Putney',
  'Quaid Block',
  "Queen's Park",
  'Raynes Park',
  'RB of Greenwich',
  'RB of Kingston upon Thames',
  'Richmond',
  'Rotherhithe',
  'Sands End',
  'Shadwell',
  "Shepherd's Bush",
  'Shoreditch',
  'Soho',
  'Somers Town',
  'South Bank',
  'South Kensington',
  'South Lambeth',
  'Southfields',
  'Southwark',
  'Spitalfields',
  "St George's Fields",
  "St. James's",
  "St. John's Wood",
  "St. Luke's",
  'St. Pancras',
  'Stepney',
  'Stepney Green',
  'Stockwell',
  'Stoke Newington',
  'Stratford',
  'Streatham',
  'Sweet Auburn',
  'Sydenham',
  'The West End',
  'Tulse Hill',
  'Tyburnia',
  'Upper Tooting',
  'Vassal',
  'Vauxhall',
  'Walthamstow',
  'Walworth',
  'Wandsworth',
  'Wapping',
  'West Norwood',
  'Westbourne Green',
  'Westminster',
  'Whitechapel',
  'Whitechapel/Brick Lane',
  'Wimbledon'];

var BOROUGHS_WITH_UNKNOWN = [...BOROUGHS, "Unknown"];

var PROPERTY_TYPES = ['Barn', 'Boat', 'Camper/RV', 'Campsite', 'Casa particular', 'Castle',
  'Earthen home', 'Entire bungalow', 'Entire cabin', 'Entire chalet', 'Entire condo', 'Entire cottage',
  'Entire guest suite', 'Entire guesthouse', 'Entire home', 'Entire home/apt', 'Entire loft', 'Entire place',
  'Entire rental unit', 'Entire serviced apartment', 'Entire townhouse', 'Entire vacation home', 'Entire villa', 'Floor',
  'Houseboat', 'Hut', 'Island', 'Minsu', 'Private room', 'Private room in bed and breakfast', 'Private room in boat',
  'Private room in bungalow', 'Private room in cabin', 'Private room in casa particular', 'Private room in castle',
  'Private room in chalet', 'Private room in condo', 'Private room in cottage', 'Private room in earthen home',
  'Private room in floor', 'Private room in guest suite', 'Private room in guesthouse', 'Private room in home',
  'Private room in hostel', 'Private room in houseboat', 'Private room in hut', 'Private room in lighthouse',
  'Private room in loft', 'Private room in religious building', 'Private room in rental unit',
  'Private room in serviced apartment', "Private room in shepherd's hut", 'Private room in tiny home',
  'Private room in townhouse', 'Private room in treehouse', 'Private room in vacation home', 'Private room in villa',
  'Private room in yurt', 'Religious building', 'Room in aparthotel', 'Room in bed and breakfast', 'Room in boutique hotel',
  'Room in hostel', 'Room in hotel', 'Room in rental unit', 'Room in serviced apartment', 'Shared room',
  'Shared room in bed and breakfast', 'Shared room in boutique hotel', 'Shared room in bungalow', 'Shared room in condo',
  'Shared room in earthen home', 'Shared room in farm stay', 'Shared room in guest suite', 'Shared room in guesthouse',
  'Shared room in home', 'Shared room in hostel', 'Shared room in hotel', 'Shared room in religious building',
  'Shared room in rental unit', 'Shared room in townhouse', 'Shepherd’s hut', 'Shipping container', 'Tent', 'Tiny home',
  'Treehouse'];

var ROOM_TYPES = ['Entire home/apt', 'Private room', 'Shared room'];